Improves the README
WitchyCat/Enfaria pull request #54
Opened 2021-01-16 14:16 UTC by Elinvynia

2021-01-16 20:00 UTC, meesha7 requested changes
I think we should keep the part about configuring the database or at least put it in some other file?

2021-01-16 20:05 UTC, Elinvynia commented
> 
> 
> I think we should keep the part about configuring the database or at least put it in some other file?

I think it goes in line with how other repositories do these things, a general overview of how to get up and running without the exact steps in detail ("doubleclick this then..." vs "install X")

2021-01-17 08:35 UTC, meesha7 commented
Ok then we'll make the setup script and put it there

2021-01-17 08:36 UTC, meesha7 approved these changes

2021-01-17 08:36 UTC, merged